server.port=8080
server.threads=10
db.url=jdbc:mysql://localhost:3306/charity_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Minsk
db.user=root
db.password=76547654
db.pool.size=5